// // 예외처리
// // try 코드블록
// try {
//   // 원래 실행할 코드

//   // 오류가 발생할만한 코드를 작성

//   // catch 코드 블록
//   console.log(number);
// } catch (error) {
//   // catch 코드 블록
//   // try 코드 블록이 오류가 발생할 떄
//   // 실행할 코드
//   console.log(error.name);
//   console.log(error.message);
// } finally {
//   // finally 코드 블록
//   console.log("무조건 실행되는 코드 1")
// }
//   console.log("무조건 실행되는 코드 2")

//   function errorFunction(){try {}}